name: Build and Test C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore Projeto-DotNetAppWin.sln

    - name: Build solution
      run: msbuild Projeto-DotNetAppWin.sln /p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe **\*Test*.dll