
name: Build and Test C# Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore Projeto-DotNetAppWin.sln

    - name: Build solution
      run: msbuild Projeto-DotNetAppWin.sln /p:Configuration=Release
      
    - name: Echo the secret
      env:
        AGITHUB_TOKEN: ${{ secrets.AGITHUB_TOKEN }}
      run: echo "The secret token is set (value hidden for security)."

    
